project:
  type: website
  output-dir: docs

website:
  title: "Mmesoma Ejiofor"
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
        
      - href: cv.qmd
        text: "{{< fa user-tie >}} CV"
        
    right:
      - href: Contact.qmd
        text: "{{< fa envelope >}} Contact"
     
format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual
